/**
 * Where rendered videos live.
 *
 * DELIBERATE: this is an ephemeral in-container directory, not a persistent
 * disk and not an external object store. The Render free plan cannot attach a
 * disk at all, and it spins the container down after 15 minutes idle, which
 * wipes the filesystem. A finished video only has to outlive the chat session
 * that produced it - reaching for S3 or a blob store to survive a restart
 * would be paid scope this project has explicitly ruled out.
 *
 * Because the container has 512 MB and no disk quota of its own, retention is
 * capped hard: every write prunes the directory back to MAX_FILES / MAX_BYTES,
 * oldest first. Without that, a busy afternoon fills the instance and the next
 * render dies on ENOSPC.
 */

import { createReadStream } from "node:fs";
import { mkdir, readdir, stat, unlink } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

export const OUT_DIR = process.env.VIDEO_OUT_DIR ?? path.join(os.tmpdir(), "ugc-renders");

const MAX_FILES = Number(process.env.OUT_MAX_FILES ?? 12);
const MAX_BYTES = Number(process.env.OUT_MAX_BYTES ?? 120 * 1024 * 1024);

/** Ids are generated by us, but they arrive back through a URL path segment. */
const ID = /^[A-Za-z0-9_-]{6,64}$/;

export function isValidId(id: string): boolean {
  return ID.test(id);
}

export async function ensureOutDir(): Promise<string> {
  await mkdir(OUT_DIR, { recursive: true });
  return OUT_DIR;
}

export function videoPath(id: string): string {
  if (!isValidId(id)) throw new Error(`invalid video id: ${id}`);
  // Basename only - the id can never climb out of OUT_DIR.
  return path.join(OUT_DIR, `${path.basename(id)}.mp4`);
}

/** Served by app/api/video/[id], not from /public - see the route for why. */
export function videoUrl(id: string): string {
  return `/api/video/${id}`;
}

/**
 * A still from the video, used as the player's poster.
 *
 * Without one the payoff moment is a grey rectangle until enough of the file
 * has buffered to paint a frame - on a slow connection that reads as broken.
 */
export function posterPath(id: string): string {
  if (!isValidId(id)) throw new Error(`invalid video id: ${id}`);
  return path.join(OUT_DIR, `${path.basename(id)}.jpg`);
}

export function posterUrl(id: string): string {
  return `/api/video/${id}?poster=1`;
}

export type Pruned = { deleted: string[]; keptFiles: number; keptBytes: number };

/** Trims the output directory back under both caps, oldest first. */
export async function prune(): Promise<Pruned> {
  await ensureOutDir();

  let entries: string[];
  try {
    entries = await readdir(OUT_DIR);
  } catch {
    return { deleted: [], keptFiles: 0, keptBytes: 0 };
  }

  const files: { name: string; mtime: number; size: number }[] = [];
  for (const name of entries) {
    if (!name.endsWith(".mp4")) continue;
    try {
      const s = await stat(path.join(OUT_DIR, name));
      files.push({ name, mtime: s.mtimeMs, size: s.size });
    } catch {
      // Vanished between readdir and stat - nothing to account for.
    }
  }

  // Newest first, then keep taking while both budgets hold.
  files.sort((a, b) => b.mtime - a.mtime);

  const deleted: string[] = [];
  let keptFiles = 0;
  let keptBytes = 0;

  for (const f of files) {
    const wouldFit = keptFiles < MAX_FILES && keptBytes + f.size <= MAX_BYTES;
    if (wouldFit) {
      keptFiles++;
      keptBytes += f.size;
      continue;
    }
    try {
      await unlink(path.join(OUT_DIR, f.name));
      // The poster is worthless without its video.
      await unlink(path.join(OUT_DIR, f.name.replace(/\.mp4$/, ".jpg"))).catch(() => {});
      deleted.push(f.name);
    } catch {
      // Already gone, or in use. Counting it as kept would be a lie, but
      // failing the render over a stale temp file would be worse.
    }
  }

  return { deleted, keptFiles, keptBytes };
}

export async function videoStat(id: string): Promise<{ size: number; mtimeMs: number } | null> {
  try {
    const s = await stat(videoPath(id));
    return s.isFile() ? { size: s.size, mtimeMs: s.mtimeMs } : null;
  } catch {
    return null;
  }
}

export function videoStream(id: string, start?: number, end?: number) {
  return createReadStream(videoPath(id), start === undefined ? undefined : { start, end });
}
