/**
 * Regenerates fixtures/ deterministically.
 *
 *   npm run fixtures
 *
 * The fixtures are committed binaries, so they need provenance: this script is
 * how they were made and how to remake them. No network, no keys.
 *
 * The sticker is built as SVG frames rasterised by sharp rather than with
 * ffmpeg's drawbox. drawbox composites colour onto a transparent RGBA base
 * without ever raising the destination alpha, which silently yields a GIF that
 * is 100% transparent - it probes as valid bgra with the right frame count and
 * draws absolutely nothing. SVG carries real alpha.
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

import { textCardPng } from "../lib/text";
import { opaquePixels } from "../lib/media";

const exec = promisify(execFile);
const FIXTURES = path.join(process.cwd(), "fixtures");
const ff = (args: string[]) => exec("ffmpeg", ["-y", "-hide_banner", "-loglevel", "error", ...args]);

/** Background: landscape on purpose, so the cover-crop path is exercised. */
async function background() {
  await ff([
    "-f", "lavfi",
    "-i", "gradients=s=1920x1080:speed=0.08:n=4:d=6:r=30,format=yuv420p",
    "-c:v", "libx264", "-preset", "veryfast", "-crf", "28", "-t", "6",
    path.join(FIXTURES, "bg.mp4"),
  ]);
}

/** 15s so the renderer's trim and fade-out are genuinely exercised. */
async function audio() {
  await ff([
    "-f", "lavfi", "-i", "sine=frequency=220:duration=15",
    "-f", "lavfi", "-i", "sine=frequency=330:duration=15",
    "-filter_complex", "[0:a][1:a]amix=inputs=2,tremolo=f=4:d=0.6,volume=0.5[a]",
    "-map", "[a]", "-c:a", "libmp3lame", "-b:a", "128k",
    path.join(FIXTURES, "audio.mp3"),
  ]);
}

function stickerFrameSvg(t: number): string {
  const cx = 200 + 90 * Math.sin(2 * Math.PI * t);
  const cy = 200 + 40 * Math.cos(4 * Math.PI * t);
  const ox = 200 - 110 * Math.sin(2 * Math.PI * t);
  const spin = (t * 360).toFixed(1);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="0 0 400 400">
  <rect x="${(cx - 70).toFixed(1)}" y="${(cy - 70).toFixed(1)}" width="140" height="140" rx="28"
        fill="#ff2eb0" stroke="#ffffff" stroke-width="8"
        transform="rotate(${spin} ${cx.toFixed(1)} ${cy.toFixed(1)})"/>
  <circle cx="${ox.toFixed(1)}" cy="200" r="30" fill="#25e5ff" stroke="#ffffff" stroke-width="6"/>
</svg>`;
}

/** Transparent animated GIF, assembled from alpha PNG frames. */
async function sticker() {
  const frames = 30;
  const tmp = path.join(FIXTURES, ".sticker-frames");
  await rm(tmp, { recursive: true, force: true });
  await mkdir(tmp, { recursive: true });

  for (let i = 0; i < frames; i++) {
    const svg = stickerFrameSvg(i / frames);
    await sharp(Buffer.from(svg)).png().toFile(path.join(tmp, `f${String(i).padStart(3, "0")}.png`));
  }

  await ff([
    "-framerate", "15",
    "-i", path.join(tmp, "f%03d.png"),
    "-filter_complex",
    "split[a][b];[a]palettegen=reserve_transparent=1:stats_mode=full[p];[b][p]paletteuse=alpha_threshold=128",
    "-loop", "0",
    path.join(FIXTURES, "sticker.gif"),
  ]);

  await rm(tmp, { recursive: true, force: true });
}

/** Static text-card fixture, produced by the real generator. */
async function textCard() {
  await textCardPng({
    text: "Fixture text card",
    kicker: "fixtures",
    variant: "hook",
    width: 1080,
    height: 1920,
    out: path.join(FIXTURES, "text.png"),
  });
}

async function main() {
  await mkdir(FIXTURES, { recursive: true });
  await background();
  await audio();
  await sticker();
  await textCard();

  const opaque = await opaquePixels(path.join(FIXTURES, "sticker.gif"));
  await writeFile(
    path.join(FIXTURES, "README.md"),
    `# Fixtures\n\nGenerated by \`npm run fixtures\` (scripts/make-fixtures.ts). No network, no keys.\n\n` +
      `| file | what | why |\n|---|---|---|\n` +
      `| bg.mp4 | 6s 1920x1080 gradient | landscape on purpose, so the cover-crop path is exercised |\n` +
      `| sticker.gif | 2s 400x400 transparent GIF | stands in for a Giphy sticker; carries real alpha |\n` +
      `| audio.mp3 | 15s tone bed | longer than the video, so trim + fade are exercised |\n` +
      `| text.png | 1080x1920 transparent card | produced by lib/text.ts |\n\n` +
      `sticker.gif frame 0 has **${opaque.toLocaleString()}** opaque pixels. If that ever reads 0 the\n` +
      `sticker is invisible and the render will look fine to a codec check while missing its hero layer.\n`
  );

  console.log(`fixtures written. sticker opaque pixels in frame 0: ${opaque}`);
  if (opaque === 0) {
    console.error("FAIL: sticker is fully transparent");
    process.exit(1);
  }
}

// Guarded: importing this module must never regenerate fixtures as a side
// effect. It did once, and rewrote bg.mp4 underneath a running render.
if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
